config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
 
 get '/admin' => 'admin/homes#top'
 
 root to: 'public/homes#top'
 get '/about' => 'public/homes#about'
 get '/customers/my_page' => 'public/customers#show'
 
 scope module: :public do
   resources :customers, only: [:edit, :update] do
     collection do
      get :unsubscribe
      patch :withdraw
     end
    end
    resources :addresses, except: [:new, :show]
    resources :items, only: [:index, :show]
    resources :cart_items, except: [:new, :show, :edit] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, except: [:edit, :update, :destroy] do
      collection do
        post :confirm
        get :complete
      end
    end
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
	
	belongs_to :genre
	has_many :order_details
	has_many :cart_items
	has_one_attached :image
	
	validates :name, presence: true
	validates :introduction, presence: true
	validates :price, presence: true
	validates :image, presence: true
	
	def with_tax_price
		(price * 1.1).floor
	end
	
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
	before_action :authenticate_admin!
	
	def index
		@items = Item.page(params[:page])	
	end
	
	def new
		@item = Item.new
	end
	
	def create
		item = Item.new(item_params)
		if item.save
			redirect_to admin_item_path(item.id)
		else
			render :new
		end
	end
	
	def show
		@item = Item.find(params[:id])
	end
	
	def edit
		@item = Item.find(params[:id])	
	end
	
	def update
		@item = Item.find(params[:id])
		if @item.update(item_params)
			redirect_to admin_item_path(@item.id)
		else
			render :edit
		end
	end
	
	private
	
	def item_params
		params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
	end
	
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8">
			<h1>商品編集</h1>
			<%= form_with model: @item,url: admin_item_path(@item.id) do |f| %>
				<table class="table table-borderless">
					<tbody>
						<tr>
							<th>商品画像</th>
							<td><%= f.file_field :image, accept: "image/*" %></td>
						</tr>
						<tr>
							<th>商品名</th>
							<td><%= f.text_field :name %></td>
						</tr>
						<tr>
							<th>商品説明</th>
							<td><%= f.text_area :introduction %></td>
						</tr>
						<tr>
							<th>ジャンル</th>
							<td><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
						</tr>
						<tr>
							<th>税抜価格</th>
							<td><%= f.text_field :price %>円</td>
						</tr>
						<tr>
							<th>販売ステータス</th>
							<td>
								<%= f.radio_button :is_active, true %>
								<%= f.label :is_active, "販売中", value: true %>
								<%= f.radio_button :is_active, false %>
								<%= f.label :is_active, "販売停止中", value: false %>
							</td>
						</tr>
					</tbody>
				</table>
				<div class="actions">
					<%= f.submit '変更を保存', class: 'btn btn-success' %>
				</div>
			<% end %>
		</div>
	</div>
</div>

	
	
	

app/views/admin/items/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h1>
				商品一覧
				<%= link_to new_admin_item_path do %>
					<i class="fas fa-plus-circle"></i>
				<% end %>
			</h1>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<table class="table table-borderless">
				<thead class="thead-light">
					<tr>
						<th scope="col1">商品ID</th>
						<th scope="col1">商品名</th>
						<th scope="col1">税抜価格</th>
						<th scope="col1">ジャンル</th>
						<th scope="col1">ステータス</th>
					</tr>
				</thead>
				
				<tbody>
					<% @items.each do |item| %>
					<tr>
						<td><%= item.id %></td>
						<td>
							<%= link_to admin_item_path(item.id) do %>
								<%= item.name %>
							<% end %>
						</td>
						<td><%= item.price.to_s(:delimited) %></td>
						<td><%= item.genre.name %></td>
						<td>
							<% if item.is_active %>
								<p class="text-success">販売中</p>
							<% else %>
								<p class="text-secondary">販売停止中</p>
							<% end %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
			
			<%= paginate @items %>
		</div>
	</div>
</div>



	

app/views/admin/items/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8">
			<h1>商品新規登録</h1>
			<%= form_with model: @item,url: admin_items_path do |f| %>
			<table class="table table-borderless">
				<tbody>
					<tr>
						<th>商品画像</th>
						<td><%= f.file_field :image, accept: "image/*" %></td>
					</tr>
					<tr>
						<th>商品名</th>
						<td><%= f.text_field :name, :placeholder => "商品名", size:20 %></td>
					</tr>
					<tr>
						<th>商品説明</th>
						<td><%= f.text_area :introduction, :placeholder => "ここに説明文を記述します" %></td>
					</tr>
					<tr>
						<th>ジャンル</th>
						<td><%= f.collection_select :genre_id, Genre.all, :id, :name, { prompt: '選択してください' } %></td>
					</tr>
					<tr>
						<th>税抜価格</th>
						<td><%= f.text_field :price, :placeholder => "1000", size: 20 %>円</td>
					</tr>
					<tr>
						<th>販売ステータス</th>
						<td>
							<%= f.radio_button :is_active, true %>
							<%= f.label :is_active, "販売中", value: true %>
							<%= f.radio_button :is_active, false %>
							<%= f.label :is_active, "販売停止中", value: false %>
						</td>
					</tr>
				</tbody>
			</table>
			<div class="actions">
				<%= f.submit '新規登録', class: 'btn btn-success' %>
			</div>
		<% end %>
		</div>
	</div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
	<div class="row">
		<h1>商品詳細</h1>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-4">
			<%= image_tag @item.image, size: "250x250" %>
		</div>
		<div class="col-md-8">
			<table class="table table-borderless">
				<tbody>
					<tr>
						<th>商品名</th>
						<td><%= @item.name %></td>
					</tr>
					<tr>
						<th>商品説明</th>
						<td><%= @item.introduction %></td>
					</tr>
					<tr>
						<th>ジャンル</th>
						<td><%= @item.genre.name %></td>
					</tr>
					<tr>
						<th>税込価格(税抜価格)</th>
						<td>
							<%= @item.with_tax_price.to_s(:delimited) %>
							(<%= @item.price.to_s(:delimited) %>)円
						</td>
					</tr>
					<tr>
						<th>販売ステータス</th>
						<td>
							<% if @item.is_active %>
								<p class="text-success">販売中</p>
							<% else %>
								<p class="text-secondary">販売停止中</p>
							<% end %>	
						</td>
					</tr>
				</tbody>
			</table>
			
			<div class="adtions">
				<%= link_to "編集する", edit_admin_item_path(@item.id), class: 'btn btn-success' %>
			</div>	
		</div>
	</div>
</div>