config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
 
 get '/admin' => 'admin/homes#top'
 
 root to: 'public/homes#top'
 get '/about' => 'public/homes#about'
 get '/customers/my_page' => 'public/customers#show'
 
 scope module: :public do
   resources :customers, only: [:edit, :update] do
     collection do
      get :unsubscribe
      patch :withdraw
     end
    end
    resources :addresses, except: [:new, :show]
    resources :items, only: [:index, :show]
    resources :cart_items, except: [:new, :show, :edit] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, except: [:edit, :update, :destroy] do
      collection do
        post :confirm
        get :complete
      end
    end
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders
  has_many :addresses
  has_many :cart_items
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  
  def active_for_authentication?
    super && (is_active == false)
  end
  
  def full_name
    last_name + ' ' + first_name
  end
  
  def full_name_kana
    last_name_kana + ' ' + first_name_kana
  end
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
	before_action :authenticate_admin!
	
	def index
		@customers = Customer.page(params[:page])
	end
	
	def show
		@customer = Customer.find(params[:id])	
	end
	
	def edit
		@customer = Customer.find(params[:id])	
	end
	
	def update
		@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
			redirect_to admin_customer_path(@customer.id)
		else
			render :edit
		end
	end
	
	private
	
	def customer_params
		params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
	end
	
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10">
			<h1><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h1>
			<%= form_with model: @customer, url: admin_customer_path(@customer.id) do |f| %>
				<table class="table table-borderless">
					<tbody>
						<tr>
							<th>会員ID</th>
							<td><%= @customer.id %></td>
						</tr>
						<tr>
							<th>氏名</th>
							<td><%= f.text_field :last_name, size: 20 %><%= f.text_field :first_name, size: 20 %></td>
						</tr>
						<tr>
							<th>フリガナ</th>
							<td><%= f.text_field :last_name_kana, size: 20 %><%= f.text_field :first_name_kana, size: 20 %></td>
						</tr>
						<tr>
							<th>郵便番号</th>
							<td><%= f.text_field :postal_code, size: 20 %></td>
						</tr>
						<tr>
							<th>住所</th>
							<td><%= f.text_field :address, size: 50 %></td>
						</tr>
						<tr>
							<th>電話番号</th>
							<td><%= f.text_field :telephone_number, size: 20 %></td>
						</tr>
						<tr>
							<th>メールアドレス</th>
							<td><%= f.text_field :email, size: 20 %></td>
						</tr>
						<tr>
							<th>会員ステータス</th>
							<td>
								<%= f.radio_button :is_active, false %>
								<%= f.label :is_active, "有効", value: false %>
								<%= f.radio_button :is_active, true %>
								<%= f.label :is_active, "退会", value: true %>
							</td>
						</tr>
					</tbody>
				</table>
				<div class="actions">
					<%= f.submit '変更を保存', class:'btn btn-success' %>	
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1>会員一覧</h1>

			<table class="table">
				<thead class="thead-light">
					<tr>
						<th>会員ID</th>
						<th>氏名</th>
						<th>メールアドレス</th>
						<th>ステータス</th>
					</tr>
				</thead>
				
				<tbody>
					<% @customers.each do |customer| %>
					<tr>
						<th><%= customer.id %></th>
						<th>
							<%= link_to admin_customer_path(customer.id) do %>
								<%= customer.full_name %>
							<% end %>
						</th>
						<th><%= customer.email %></th>
						<th>
							<% if customer.is_active %>
								<p class="text-secondary">退会</p>
							<% else %>
								<p class="text-success">有効</p>
							<% end %>
						</th>
					</tr>
					<% end %>
				</tbody>
			</table>
			
			<%= paginate @customers %>
		</div>
	</div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10">
			<h1><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h1>

			<table class="table table-borderless">
				<tbody>
					<tr>
						<th>会員ID</th>
						<td><%= @customer.id %></td>
					</tr>
					<tr>
						<th>氏名</th>
						<td><%= @customer.full_name %></td>
					</tr>
					<tr>
						<th>フリガナ</th>
						<td><%= @customer.full_name_kana %></td>
					</tr>
					<tr>
						<th>郵便番号</th>
						<td><%= @customer.postal_code %></td>
					</tr>
					<tr>
						<th>住所</th>
						<td><%= @customer.address %></td>
					</tr>
					<tr>
						<th>電話番号</th>
						<td><%= @customer.telephone_number %></td>
					</tr>
					<tr>
						<th>メールアドレス</th>
						<td><%= @customer.email %></td>
					</tr>
					<tr>
						<th>会員ステータス</th>
						<td>
							<% if @customer.is_active %>
								<p class="text-secondary">退会</p>
							<% else %>
								<p class="text-success">有効</p>
							<% end %>	
						</td>
					</tr>
				</tbody>
			</table>
			
			<div class="actions">
				<%= link_to '編集する', edit_admin_customer_path(@customer.id), class: 'btn btn-success' %>
				<%= link_to '注文履歴一覧を見る', admin_path, class: 'btn btn-primary' %>
			</div>
		</div>
	</div>
</div>