config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
 
 get '/admin' => 'admin/homes#top'
 
 root to: 'public/homes#top'
 get '/about' => 'public/homes#about'
 get '/customers/my_page' => 'public/customers#show'
 
 scope module: :public do
   resources :customers, only: [:edit, :update] do
     collection do
      get :unsubscribe
      patch :withdraw
     end
    end
    resources :addresses, except: [:new, :show]
    resources :items, only: [:index, :show]
    resources :cart_items, except: [:new, :show, :edit] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, except: [:edit, :update, :destroy] do
      collection do
        post :confirm
        get :complete
      end
    end
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	has_many :order_details
	
	enum payment_method: { credit_card: 0, transfer: 1 }
	enum status: { not_payment: 0, payment_confirmation: 1, in_the_making: 2, ready_to_ship:3, shipped: 4 } 
	
	validates :payment_method, presence: true
	validates :postal_code, presence: true
	validates :address, presence: true
	validates :name, presence: true
	validates :shipping_cost, presence: true
	validates :total_payment, presence: true
	validates :status, presence: true
	
	def total_cost
		total_payment - shipping_cost
	end
	
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	before_action :authenticate_admin!
	
	def show
		@order = Order.find(params[:id])
	end
	
	def update
		@order = Order.find(params[:id])
		@order.update(order_params)
		if @order.status == "payment_confirmation"
			@order.order_details.update_all(making_status: "preparation")
			redirect_to admin_order_path(@order.id)
		else
			redirect_to admin_order_path
		end
	end
	
	private
	
	def order_params
		params.require(:order).permit(:status)
	end
	
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10">
			<h1>注文履歴詳細</h1>
			<table class="table table-borderless">
				<tbody>
					<tr>
						<th>購入者</th>
						<td>
							<%= link_to admin_customer_path(@order.customer_id) do %>
								<%= @order.customer.full_name %>
							<% end %>
						</td>
					</tr>
					<tr>
						<th>注文日</th>
						<td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
					</tr>
					<tr>
						<th>配送先</th>
						<td>
							〒<%= @order.postal_code %>
							<%= @order.address %><br>
							<%= @order.name %>
						</td>
					</tr>
					<tr>
						<th>支払方法</th>
						<td><%= @order.payment_method_i18n %></td>
					</tr>
					<tr>
						<th>注文ステータス</th>
						<td>
							<%= form_with model: @order, url: admin_order_path(@order.id) do |f| %>
								<%= f.select :status, Order.statuses_i18n.invert %>
								<%= f.submit '更新', class: "btn btn-success" %>
							<% end %>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-9">
			<table class="table table-borderless">
				<thead class="thead-light">
					<tr>
						<th>商品名</th>
						<th>単価(税込)</th>
						<th>数量</th>
						<th>小計</th>
						<th>製作ステータス</th>
					</tr>
				</thead>
				<tbody>
					<% @order.order_details.each do |order_detail| %>
					<tr>
						<td><%= order_detail.item.name %></td>
						<td><%= order_detail.item.with_tax_price.to_s(:delimited) %></td>
						<td><%= order_detail.amount %></td>
						<td><%= order_detail.subtotal.to_s(:delimited) %></td>
						<td>
							<%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch do |f| %>
								<%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
								<%= f.hidden_field :order_detail_id, :value => order_detail.id %>
								<%= f.submit '更新', class: "btn btn-success" %>
							<% end %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>	
		</div>
		<div class="col-md-3">
			<table class="table table-borderless">
				<tbody>
					<tr>
						<th>商品合計</th>
						<td><%= @order.total_cost.to_s(:delimited) %></td>
					</tr>
					<tr>
						<th>送料</th>
						<td><%= @order.shipping_cost %></td>
					</tr>
					<tr>
						<th>請求金額合計</th>
						<td><%= @order.total_payment.to_s(:delimited) %></td>
					</tr>
				</tbody>
			</table>	
		</div>
	</div>
</div>