config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
 
 get '/admin' => 'admin/homes#top'
 
 root to: 'public/homes#top'
 get '/about' => 'public/homes#about'
 get '/customers/my_page' => 'public/customers#show'
 
 scope module: :public do
   resources :customers, only: [:edit, :update] do
     collection do
      get :unsubscribe
      patch :withdraw
     end
    end
    resources :addresses, except: [:new, :show]
    resources :items, only: [:index, :show]
    resources :cart_items, except: [:new, :show, :edit] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, except: [:edit, :update, :destroy] do
      collection do
        post :confirm
        get :complete
      end
    end
  end
  
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :customer
	
	validates :postal_code, presence: true
	validates :address, presence: true
	validates :name, presence: true
	
	def address_display
		'〒' + postal_code + ' ' + address + ' ' + name
	end
	
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	
	belongs_to :customer
	belongs_to :item
	
	validates :item_id, presence: true
	validates :customer_id, presence: true
	validates :amount, presence: true
	
	def subtotal
		item.with_tax_price * amount
	end
	
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders
  has_many :addresses
  has_many :cart_items
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  
  def active_for_authentication?
    super && (is_active == false)
  end
  
  def full_name
    last_name + ' ' + first_name
  end
  
  def full_name_kana
    last_name_kana + ' ' + first_name_kana
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
	
	has_many :items
	
	validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
	
	belongs_to :genre
	has_many :order_details
	has_many :cart_items
	has_one_attached :image
	
	validates :name, presence: true
	validates :introduction, presence: true
	validates :price, presence: true
	validates :image, presence: true
	
	def with_tax_price
		(price * 1.1).floor
	end
	
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	has_many :order_details
	
	enum payment_method: { credit_card: 0, transfer: 1 }
	enum status: { not_payment: 0, payment_confirmation: 1, in_the_making: 2, ready_to_ship:3, shipped: 4 } 
	
	validates :payment_method, presence: true
	validates :postal_code, presence: true
	validates :address, presence: true
	validates :name, presence: true
	validates :shipping_cost, presence: true
	validates :total_payment, presence: true
	validates :status, presence: true
	
	def total_cost
		total_payment - shipping_cost
	end
	
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
	belongs_to :item
	
	enum making_status: { not_making: 0, preparation: 1, making: 2, making_complete: 3 }
	
	validates :item_id, presence: true
	validates :order_id, presence: true
	validates :price, presence: true
	validates :amount, presence: true
	validates :making_status, presence: true
	
	def subtotal
		item.with_tax_price * amount
	end
	
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
	before_action :authenticate_admin!
	
	def index
		@genres = Genre.all
		@genre = Genre.new
	end
	
	def create
		@genre = Genre.new(genre_params)
		if @genre.save
			redirect_to admin_genres_path
		else
			@genres = Genre.all
			render :index
		end
	end
	
	def edit
		@genre = Genre.find(params[:id])
	end
	
	def update
		genre = Genre.find(params[:id])
		if genre.update(genre_params)
			redirect_to admin_genres_path
		else
			render :edit
		end
	end
	
	private
	
	def genre_params
		params.require(:genre).permit(:name)
	end
	
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
	before_action :authenticate_admin!
	
	def top
		@orders = Order.page(params[:page])	
	end	
	
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
	before_action :authenticate_admin!
	
	def index
		@items = Item.page(params[:page])	
	end
	
	def new
		@item = Item.new
	end
	
	def create
		item = Item.new(item_params)
		if item.save
			redirect_to admin_item_path(item.id)
		else
			render :new
		end
	end
	
	def show
		@item = Item.find(params[:id])
	end
	
	def edit
		@item = Item.find(params[:id])	
	end
	
	def update
		@item = Item.find(params[:id])
		if @item.update(item_params)
			redirect_to admin_item_path(@item.id)
		else
			render :edit
		end
	end
	
	private
	
	def item_params
		params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	
	

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NAGANOCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.jpg') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavdropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <li class="nav-item">
                  <%= link_to "マイページ", customers_my_page_path, class: "btn btn-outline-warning" %>
                </li>
                <li class="nav-item">
                  <%= link_to "商品一覧", items_path, class: "btn btn-outline-warning" %>
                </li>
                <li class="nav-item">
                  <%= link_to "カート", cart_items_path, class: "btn btn-outline-warning" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-warning" %>
                </li>
                ようこそ、<%= current_customer.last_name %>さん!
              <% elsif  admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-warning" %>
                </li>
                <li class="nav-item">
                  <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-warning" %>
                </li>
                <li class="nav-item">
                  <%= link_to "注文履歴一覧", admin_path, class: "btn btn-outline-warning" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-warning" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-warning" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "About", about_path, class: "btn btn-outline-warning" %>
                </li>
                <li class="nav-item">
                  <%= link_to "商品一覧", items_path, class: "btn btn-outline-warning" %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-warning" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-warning" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <main>
      <%= yield %>
    </main>
    
    <footer class="footer">

    </footer>
    </div>
  </body>
</html>